if(EXISTS "C:/Users/Rakete/Documents/Drohnenversuchsstand/DROMA/Simulation/scripts/sitl/build_cg/test_mcu_model_e3b0c442_MinSizeRel_tests.cmake")
  include("C:/Users/Rakete/Documents/Drohnenversuchsstand/DROMA/Simulation/scripts/sitl/build_cg/test_mcu_model_e3b0c442_MinSizeRel_tests.cmake")
else()
  add_test(test_mcu_model_NOT_BUILT test_mcu_model_NOT_BUILT)
endif()
